apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-postgresql
spec:
  selector:
    matchLabels:
      app: hive-postgresql
  replicas: 1
  template:
    metadata:
      labels:
        app: hive-postgresql
    spec:
      containers:
        - name: postgres
          image: registry.redhat.io/rhel8/postgresql-12 # image that works on OpenShift 4 but requires pull secret
          #image: postgres:12 # image that works on raw Kube but not OpenShift
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: hive-postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data:z
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: hive-postgresql
