---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-config
  labels:
    app: postgres
type: Opaque
stringData:
  # Vars for registry.redhat.io container:
  POSTGRESQL_DATABASE: hive
  POSTGRESQL_USER: hive
  POSTGRESQL_PASSWORD: helloworld
  # Vars for upstream docker.io postgres container:
  POSTGRES_DB: hive
  POSTGRES_USER: hive
  POSTGRES_PASSWORD: helloworld
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          #image: registry.redhat.io/rhel8/postgresql-12
          image: postgres:12
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data:z
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  ports:
   - port: 5432
  selector:
   app: postgres
